services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: kimpay-pb
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public
      - ./pb_migrations:/pb_migrations
    restart: unless-stopped

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: kimpay-app
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - ORIGIN=http://localhost:3000
    depends_on:
      - pocketbase
    restart: unless-stopped
