    container_name: kimpay-app
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - ORIGIN=http://localhost:3000
    depends_on:
      - pocketbase
    restart: unless-stopped
